[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pykit"
version = "0"
description = "Reusable Python components and utilities for my shitty applications."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests"
]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "pykit.*",
]
